development:
  user: fedoraAdmin
  password: MD5:ddb5fbfe98b0dc2cecd6b396994b77f4
  url: http://localhost:8983/marmotta/ldp
  base_path: /dev
test:
  #user: fedoraAdmin
  #password: MD5:ddb5fbfe98b0dc2cecd6b396994b77f4
  url: http://localhost:8983/marmotta/ldp
  base_path: /test
production:
  user: fedoraAdmin
  password: MD5:ddb5fbfe98b0dc2cecd6b396994b77f4
  url: http://localhost:8983/marmotta/ldp
